apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.backend_api.hpaName }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment  
    name: backend-api  
  minReplicas: {{ .Values.backend_api.autoscaling.minReplicas }}  
  maxReplicas: {{ .Values.backend_api.autoscaling.maxReplicas }} 
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.backend_api.autoscaling.targetCPUUtilizationPercentage }} 
  - type: Resource
    resource:
      name: memory
      target:
        type: AverageValue
        averageValue: {{ .Values.backend_api.autoscaling.targetMemoryUtilizationPercentage }} 