apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-backend-api-svc
spec:
  selector:
    app: {{ .Release.Name }}-backend-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 5000
  type: NodePort