apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-api
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: data-api
  template:
    metadata:
      labels:
        app: data-api
    spec:
      containers:
      - name: data-api
        image: {{ .Values.image.repository }}/data_api:{{ .Values.image.tagdata }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 5000
        securityContext:
          readOnlyRootFilesystem: {{ .Values.securityContext.readOnlyRootFilesystem }}
          runAsNonRoot: {{ .Values.securityContext.runAsNonRoot }}
          runAsUser: {{ .Values.securityContext.runAsUser }}
          allowPrivilegeEscalation: {{ .Values.securityContext.allowPrivilegeEscalation }}
      imagePullSecrets:
      - name: regcred
      volumes:
      - name: main-volume
        persistentVolumeClaim:
           claimName: task-pv-claim