apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-data-api-svc
spec:
  selector:
    app: data-api
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 5000
  type: NodePort