apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-api
spec:
  replicas: {{ .Values.data_api.replicaCount }}
  selector:
    matchLabels:
      app: data-api
  template:
    metadata:
      labels:
        app: data-api
    spec:
      containers:
      - name: data-api
        image: {{ .Values.data_api.image.repository }}/data_api:{{ .Values.data_api.image.tagdata }}
        resources:
          limits:
            cpu: {{ .Values.data_api.resources.limits.cpu }}
            memory: {{ .Values.data_api.resources.limits.memory }}
          requests:
            cpu: {{ .Values.data_api.resources.requests.cpu }}
            memory: {{ .Values.data_api.resources.requests.memory }}
        imagePullPolicy: {{ .Values.data_api.image.pullPolicy }}
        ports:
        - containerPort: 5000
        securityContext:
          readOnlyRootFilesystem: {{ .Values.data_api.securityContext.readOnlyRootFilesystem }}
          runAsNonRoot: {{ .Values.data_api.securityContext.runAsNonRoot }}
          runAsUser: {{ .Values.data_api.securityContext.runAsUser }}
          allowPrivilegeEscalation: {{ .Values.data_api.securityContext.allowPrivilegeEscalation }}
      volumes:
      - name: main-volume
        persistentVolumeClaim:
           claimName: task-pv-claim