apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.data_api.hpaName }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment  
    name: data-api  
  minReplicas: {{ .Values.data_api.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.data_api.autoscaling.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.data_api.autoscaling.targetCPUUtilizationPercentage }}
  - type: Resource
    resource:
      name: memory
      target:
        type: AverageValue
        averageValue: {{ .Values.data_api.autoscaling.targetMemoryUtilizationPercentage }}