# Default values for flask-apps.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
backend_api:
  replicaCount: 2
  image:
    repository: 816731947491.dkr.ecr.eu-west-2.amazonaws.com
    tagbackend: 998133865b6b0506a9cfccc2d05e920c0085c65c
    pullPolicy: IfNotPresent
  hpaName: backendhpa
  securityContext:
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 1000
    readOnlyRootFilesystem: true
    allowPrivilegeEscalation: false

  service:
    type: ClusterIP
    port: 80

  ingress:
    enabled: false
    className: ""
    annotations: {}
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    hosts:
      - host: chart-example.local
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local

  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80

  external_integration_keys:
    env: "dev"
    dev:
      api_key: "adsfk2123jlsjflsdf"
    staging:
      api_key: "asdf3229349jskldf"
    prod:
      api_key: "ksdlkfj392394sdfsdf"


data_api:
  replicaCount: 2
  image:
    repository: 816731947491.dkr.ecr.eu-west-2.amazonaws.com
    tagdata: 998133865b6b0506a9cfccc2d05e920c0085c65c
    pullPolicy: IfNotPresent
  hpaName: datahpa
  securityContext:
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 1000
    readOnlyRootFilesystem: true
    allowPrivilegeEscalation: false

  service:
    type: ClusterIP
    port: 80

  ingress:
    enabled: false
    className: ""
    annotations: {}
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    hosts:
      - host: chart-example.local
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local

  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80