---
- name: Get ECR login token
  command: "aws ecr get-login-password --region {{ ecr_region }}"
  environment:
    AWS_PROFILE: "default"
  register: ecr_login_password
  changed_when: false

- name: Log in to AWS ECR
  command: "docker login -u AWS -p {{ ecr_login_password.stdout }} {{ aws_account_number | b64decode }}.dkr.ecr.{{ ecr_region }}.amazonaws.com"

- name: Download Chart from repo
  command: "helm pull oci://{{ aws_account_number | b64decode }}.dkr.ecr.{{ ecr_region }}.amazonaws.com/{{ chart_image }} --version {{ version }}"

- name: Unzip the .tgz file
  ansible.builtin.unarchive:
    src: ~/{{ chart_image }}-{{ version }}.tgz
    dest: ~/
    remote_src: yes

- name: Deploy Helm to Kubernetes Cluster
  command: "helm install {{ chart_image }} ./{{ chart_image }}"
